# Generated by Django 3.2.13 on 2023-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_ownership', models.CharField(choices=[('1st ownership', '1st ownership'), ('2nd ownership', '2nd ownership'), ('3rd ownership', '3rd ownership'), ('Antique', 'Antique')], max_length=50)),
                ('product_location', models.CharField(max_length=100)),
                ('product_image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
