# Generated by Django 3.2.13 on 2023-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_product',
            name='product_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
