# Generated by Django 3.2.13 on 2023-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_sell_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_product',
            name='contact_us',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
