# Generated by Django 3.2.13 on 2023-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_sell_product_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_product',
            name='email_us',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
