# Generated by Django 3.2.13 on 2023-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_sell_product_email_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_product',
            name='contact_us',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
